sudo: false
install: true

os:
  - linux
  - osx

language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  allow_failures:
    - os: osx

branches:
  only:
  - master

script:
- make test
- make
- cd ./build
- ./hmdc -t
