sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

branches:
  only:
  - master

install: true
script:
- python ./hmdc -t
- make
- cd ./build
- ./hmdc -t
